#!/bin/bash/
mkdir iAmTechie
cd iAmTechie
touch ncs{1..100}.txt
for i in {1..100};
do echo "/home/cg/root/5088720/iAmTechie" > ncs${i}.txt;
done
cat ncs56.txt
#above statement was to check the address of ncs56
